Repository pnp/PnP-PowerShell, pull requests merged in 2020-12, with the labels that each got.

#2852 Fixing how Get-PnPFile handles removed principals in non-English environments
  CHANGELOG.md
  Commands/Files/GetFile.cs
Labels: status:checked and ready for merge ✔

#3011 Several fixes in Get-PnPSubWebs and addition of -RootWeb parameter
  CHANGELOG.md
  Commands/Web/GetSubwebs.cs
Labels: status:checked and ready for merge ✔

#2796 sourceUri is now generated using the file's folder URL instead of the file URL.(Issue 2780)
  CHANGELOG.md
  Commands/Files/CopyFile.cs
Labels: status:checked and ready for merge ✔

#2909 Add new switch parameter "-AddToAllContentTypes" to Add-PnPField to automatically add the new field to all list content types
  Commands/Fields/AddField.cs
Labels: status:Awaiting PnP Sites Core PR 🚧

#3018 Feature - header layout support in Set-PnPClientSidePage
  Commands/ClientSidePages/SetClientSidePage.cs
Labels: 🚀 Port to PnP.PowerShell

#3016 Fix for Bug #3105 - Clear-PnPRecycleBinItem help
  Commands/RecycleBin/ClearRecycleBinItem.cs
Labels: 🚀 Port to PnP.PowerShell

#2944 Fix ApplyTenantTemplate with AAD App
  Commands/Provisioning/Tenant/ApplyTenantTemplate.cs
Labels: 🚀 Port to PnP.PowerShell

#2931 Added GrouplessTeamSite enum to SiteWebTemplates
  Commands/Enums/SiteWebTemplate.cs
Labels: 🚀 Port to PnP.PowerShell
